# Generated by Django 4.1.4 on 2023-01-04 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('property_type', models.CharField(choices=[('residential property', 'Residential Property'), ('Commercial property', 'Commercial Property'), ('Industrial property', 'Industrial Property'), ('agricultural property', 'Agricultural Property'), ('recreational property', 'Recreational Property'), ('special-use property', 'Special-use Property'), ('land', 'Land')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beds', models.PositiveIntegerField()),
                ('baths', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image_urls', models.TextField(blank=True)),
                ('posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('rented', 'Rented'), ('sold', 'Sold'), ('available', 'Available')], default='available', max_length=9)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-posted'], name='accounts_pr_posted_66197e_idx'),
        ),
    ]
