# Generated by Django 4.1.4 on 2023-02-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_property_property_accounts_pr_posted_66197e_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
